name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build Docker image
      run: |
        docker build --build-arg WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} \
                     --build-arg GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
                     -t weather-app:latest .

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      run: |
        docker tag weather-app:latest bixor/weather-app:latest
        docker push bixor/weather-app:latest

    - name: SSH to EC2 and deploy
      env:
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_HOST: ${{ secrets.EC2_HOST }} 
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }} 
      run: |
        echo "$EC2_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        echo "Private key length: ${#EC2_PRIVATE_KEY}"  # Debugging
        ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem $EC2_USERNAME@$EC2_HOST << 'EOF'
          docker pull bixor/weather-app:latest
          docker stop weather-app || true 
          docker rm weather-app || true 
          docker run -d --name weather-app -p 5000:5000 bixor/weather-app:latest 
        EOF
